[parameters]
native_token = "NAAN"
min_num_of_blocks = 3600
max_expected_time_per_block = 20
max_tx_bytes = 1048576
max_proposal_bytes = 6291456
vp_allowlist = [ "8781c170ad1e3d2bbddc308b77b7a2edda3fff3bc5d746232feec968ee4fe3cd", "129ee7bee68b02bfae638da2a634b8ecbffa2cb3f46cfa8e172baf009627ec78",]
tx_allowlist = [ "5938c2b9962eb57bf309a604afc9aa6bc55851fd1791346c5c5795abaaa5f295", "40e55cdef50e0771eb2b3cfe78b841d988345113f7fbeaa8b158de04589bb9fc", "66412b1b01b6659dc196bef86bdb540181d90c2f984a13597f0aa2a4f9c9c907", "919be890123e9fbe7f85640811f3ca8edfebe94b7314118afbc84ff9c75ec488", "f76e025e52c75e34937e76fae43c6ed7544e2268e0bcdafeca0b05f9b7484b36", "1f0981a2ff60b5e9619c5464839d8d4e08dac72a8185a21285ae7f0e9498dd8c", "4af7ca07f6e6f2ad87ffe2c5fca90224544c45cc263e2e4d05775d782cac1f48", "0faaf9b55c150cdf8b2ea6a05c5fae725735b4fee44aa5da79bcd1881cb43f78", "f99df82e284dcb96a12b409bc43aa7dc77b346ab0b2d3f0a9a39807e749ce8ee", "51e79a8f5d39b40db8531610398a8631e27390d48af80c916382779d7b0e7e41", "b0a4e44eb0e8e3a1af49ebd2b0483260c67a17f974c7517904e88897279d1b29", "c94c4e6d549c921b9a483675f0e3af45eef79d4489bd35061fd285af6189b20d", "4afaa8c4ea6138a43d465ed09e86aedb16c54f63fd09a752a3aca5a26542e126", "7655ed64d1b07900672aee307f679b35af77337c077648adc11914348d1f130f", "283fd236d971dd0f7ca1a329b508a4039946f40f1c9792863fe6b0fa05d74832", "0960374d23acbac1feb27b3888095859217936c900cef54e559d215cec3206ef", "e39415d64bdc3c16f9b21ebee4e9496f8ce5cdd5551d1e611c449d8bfdcffae0", "2b1451721dcdd069a19cba1f9b338bb6a45d85d0d56ba7ca952742d3ec5878b3", "70f91d4f778d05d40c5a56490ced906b016e4b7a2a2ef5ff0ac0541ff28c5a22", "ed0ccfa4a8c8fa86f9f14c3b53b7f126ce4a86849815dad784b5aa35011a1db6", "ccdbe81f664ca6c2caa11426927093dc10ed95e75b3f2f45bffd8514fee47cd0", "69560777e2656b2872a49080c51bb5b1a498a7ffd79dae491d36b301a1b012e6",]
implicit_vp = "vp_implicit"
epochs_per_year = 730
max_signatures_per_transaction = 15
max_block_gas = 5000000
fee_unshielding_gas_limit = 20000
fee_unshielding_descriptions_limit = 15

[pos_params]
max_validator_slots = 257
pipeline_len = 2
unbonding_len = 4
tm_votes_per_token = "1"
block_proposer_reward = "0.125"
block_vote_reward = "0.1"
max_inflation_rate = "0.0"
target_staked_ratio = "0.0"
duplicate_vote_min_slash_rate = "0.001"
light_client_attack_min_slash_rate = "0.001"
cubic_slashing_window_length = 1
validator_stake_threshold = "1000000000"
liveness_window_check = 8640
liveness_threshold = "0.9"
rewards_gain_p = "0.0"
rewards_gain_d = "0.0"

[gov_params]
min_proposal_fund = 5000
max_proposal_code_size = 600000
min_proposal_voting_period = 2
max_proposal_period = 6
max_proposal_content_size = 10000
min_proposal_grace_epochs = 2

[pgf_params]
stewards = []
pgf_inflation_rate = "0.0"
stewards_inflation_rate = "0.0"

[parameters.minimum_gas_price]
naan = "0.0001"
